// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NLayerApp.Dal;

#nullable disable

namespace NLayerApp.Dal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230323192422_createDb")]
    partial class createDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NLayerApp.Core.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 3, 23, 22, 24, 22, 725, DateTimeKind.Local).AddTicks(2885),
                            Description = "Elektornik Eşyalar",
                            IsDeleted = false,
                            Name = "Elektronik Eşyalar"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 3, 23, 22, 24, 22, 725, DateTimeKind.Local).AddTicks(2892),
                            Description = "Çantalar",
                            IsDeleted = false,
                            Name = "Çantalar"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 3, 23, 22, 24, 22, 725, DateTimeKind.Local).AddTicks(2893),
                            Description = "Telefonlar",
                            IsDeleted = false,
                            Name = "Telefonlar"
                        });
                });

            modelBuilder.Entity("NLayerApp.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Code = "0001",
                            CreateDate = new DateTime(2023, 3, 23, 22, 24, 22, 725, DateTimeKind.Local).AddTicks(3062),
                            Name = "Tost Makinası",
                            Price = 1500m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Code = "00002",
                            CreateDate = new DateTime(2023, 3, 23, 22, 24, 22, 725, DateTimeKind.Local).AddTicks(3064),
                            Name = "Leptop Çantası",
                            Price = 750m,
                            Stock = 20
                        });
                });

            modelBuilder.Entity("NLayerApp.Core.Models.Product", b =>
                {
                    b.HasOne("NLayerApp.Core.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NLayerApp.Core.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
